"""add user.password_hash

Revision ID: 9cc5f5e584b4
Revises: 89644f7537d5
Create Date: 2026-06-25 17:54:57.389797

"""

from passlib.contect import CryptContext
pwd = CryptContext(schemes=["bcrypt"], deprecated ="auto")
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc5f5e584b4'
down_revision: Union[str, Sequence[str], None] = '89644f7537d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
