/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GermanLanguageRouteImport } from './routes/german-language'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UniversitiesRouteImport } from './routes/universities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GermanLanguageRoute = GermanLanguageRouteImport.update({
  id: '/german-language',
  path: '/german-language',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/auth': typeof AuthRoute
  '/german-language': typeof GermanLanguageRoute
  '/guides': typeof GuidesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/auth': typeof AuthRoute
  '/german-language': typeof GermanLanguageRoute
  '/guides': typeof GuidesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/auth': typeof AuthRoute
  '/german-language': typeof GermanLanguageRoute
  '/guides': typeof GuidesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accommodation'
    | '/auth'
    | '/german-language'
    | '/guides'
    | '/sitemap.xml'
    | '/universities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accommodation'
    | '/auth'
    | '/german-language'
    | '/guides'
    | '/sitemap.xml'
    | '/universities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accommodation'
    | '/auth'
    | '/german-language'
    | '/guides'
    | '/sitemap.xml'
    | '/universities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccommodationRoute: typeof AccommodationRoute
  AuthRoute: typeof AuthRoute
  GermanLanguageRoute: typeof GermanLanguageRoute
  GuidesRoute: typeof GuidesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/german-language': {
      id: '/german-language'
      path: '/german-language'
      fullPath: '/german-language'
      preLoaderRoute: typeof GermanLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccommodationRoute: AccommodationRoute,
  AuthRoute: AuthRoute,
  GermanLanguageRoute: GermanLanguageRoute,
  GuidesRoute: GuidesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
